server :
  address : ":8000"                         # 本地监听地址。默认":80"，多个地址以","号分隔。例如："192.168.2.3:8000,10.0.3.10:8001"
  readTimeout : "60s"                       # 请求读取超时时间，一般不需要配置。默认为60秒
  writeTimeout : "0"                        # 数据返回写入超时时间，一般不需要配置。默认不超时（0）
  idleTimeout : "60s"                       # 仅当Keep-Alive开启时有效，请求闲置时间。默认为60秒
  maxHeaderBytes : "10240"                  # 请求Header大小限制（Byte）。默认为10KB
  serverAgent : "GoFrame HTTP Server"       # 服务端Agent信息。默认为"GoFrame HTTP Server"
  logPath : "./Log"                         # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
  logStdout : false                         # 日志是否输出到终端。默认为true
  accessLogEnabled : true                   # 是否记录访问日志。默认为false
  #serverRoot : "./Public"                   # 静态文件服务的目录根路径，配置时自动开启静态文件服务。默认关闭
  pprofEnabled : true                       # 是否开启PProf性能调试特性。默认为false
  pprofPattern : "/PProf"                   # 开启PProf时有效，表示PProf特性的页面访问路径，对当前Server绑定的所有域名有效。
  clientMaxBodySize : 810241024             # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB
  formParsingMemory : 1048576               # 解析表单时的缓冲区大小(Byte)，一般不需要配置。默认为1024*1024=1MB
  nameToUriType : 0                         # 路由注册中使用对象注册时的路由生成规则。默认为0
  routeOverWrite : false                    # 当遇到重复路由注册时是否强制覆盖。默认为false，重复路由存在时将会在启动时报错退出
  dumpRouterMap : false                     # 是否在Server启动时打印所有的路由列表。默认为true
  graceful : true                           # 是否开启平滑重启特性，开启时将会在本地增加10000的本地TCP端口用于进程间通信。默认false
  gracefulTimeout : 5                       # 父进程在平滑重启后多少秒退出，默认2秒。若请求耗时大于该值，可能会导致请求中断
  authHeader: "Authorization"               # 请求头鉴权变量名称
logger :
  path : "./Log"
  file : "{Y-m-d}.log"
  prefix : ""
  level : "all"
  stdout : false
  rotateSize : "1024M"
  rotateExpire : "1d"
database :
  logger :
    path : "./Log"
    file : "sql_{Y-m-d}.log"
    level : "all"
    stdout : false
    rotateSize : "1024M"
    rotateExpire : "1d"
  default:
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "123456"
    name: "DiCloud"
    type : "mysql"
    debug: "true"
redis :
  default :
    address : "127.0.0.1:6379"
    db : 1
    pass : ""